### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by jacwright** [dabblewriter/dabble#23]
We need to discuss the role **plugins** play within Dabble.

## Plugins

Plugins are ways to customize the base product into a new tool. They *are not* meant to allow users to add new features at runtime. We may introduce a runtime concept called **extensions** for users to customize their own instance at runtime.

Plugins take the base editor and add features and types that all users will get. They get compiled into the main `app.js` and are trusted by default. This doesn't necessarily need to be how they get loaded, but the key point is they contain trusted code that the owner of a Dabble installation trusts implicitly and provide features across the entire user-base.

### Project Types

Plugins provide definitions for different types of projects. They can define types of folders and files that exist within these projects. They can define a project's default structure. They can define rules for how these folders and files are displayed and interactive with. And they can provide custom views on folders and files.

#### Example
An example is the **novel** plugin. It defines a custom structure with top-level folders:
 * Manuscript
 * Plots
 * Characters
 * Notes
 * Trash

along with a default book, chapter, and scene within the Manuscript folder.

The novel plugin defines folder types for:
 * book
 * part
 * chapter
 * plot
 * plot-line
 * cast

It defines file types for:
 * scene
 * plot-point
 * character

It defines rules for:
 * displaying a book in one continuous document with parts, chapters, and scenes and scrolling to the location of the folder/file in the document when clicked in the navigator
 * only allowing folders/files of certain types to only exist within certain folder types:
   * scenes to exist within chapters or generic folders
   * chapters to exist within parts or books
   * parts to exist within books
   * plot-points to exist within plot-lines
   * etc.

The novel plugin also defines custom views on many of these folders and files.

### Editor Customization

Plugins can also customize the editor to work in certain ways or to add metadata in the metadata pane (the right nav column). They can add custom user editing capabilities such as highlighting adverbs or auto-linking terms throughout the files.

### 3rd-Party Service Integration

Plugins can integrate 3rd-party services such as cloud storage, publishing to the Amazon kindle store, publishing to Wattpad, requesting editing services, or saving to github. The options are quite extensive.

**Comment by jacwright** [comment]
Maybe a better name for this feature is **Module** instead of Plugin.

**Comment by matthopson** [comment]
I like `Module` better.

Could a module extend the functionality of another to add additional functionality? Or would you clone the existing module and update it to suit?

**Comment by jacwright** [comment]
> Could a module extend the functionality of another to add additional functionality?

Yes, it could.

Maybe it's the change of name to module or just the desire to take advantage of existing tools, but I think using node modules to accomplish would work well. It would work like Grunt plugins and each plugin/module would be a separate repo published on NPM. In order to create a new product with Dabble you'd include it and all the plugins you need into package.json with any other customizations you want and build it from there.

**Comment by matthopson** [comment]
I like this. Kinda like `hubot` scripts. All are prefixed with `hubot-`

**Comment by matthopson** [comment]
This also forces a small amount of convention too with module submission - which is a good thing.

**Comment by jacwright** [comment]
So what's the usage pattern? Grunt is a tool you use with other applications. Hubot you create a directory with yeoman.

Dabble is a project that creates a set of files that can be hosted on a static file-server. We only run it now with `budo` for convenience in development. It has no node server or server-side app component. 100% single-page HTML5 app. What other projects are like this that we could consider?

**Comment by jacwright** [comment]
Also, we may want to create an organization for dabble modules.

**Comment by matthopson** [comment]
Obviously we need to create our own dabble module registry to build and install plugins :D

**Comment by matthopson** [comment]
It could build and then deploy to a cdn automatically when pushed to the org. You could optionally build your own plugins and include them locally.

**Comment by jacwright** [comment]
Discussion in Gitter we decided to stick with `plugins` that get loaded at runtime. A deploy of Dabble can have a default set of plugins that get loaded but writers can add/remove plugins as they see fit.
